### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by crivasestrada** [microsoft/powerplatform-actions#165]
Hi,
I would like to make a request about vulnerabilities detect in the security scan.
I have clone this repository and I have passed a security scan. The Dependabot alerts show vulnerabilities related to dependencies version included in the package-lock.json:

ansi-regex version 5.0.0 --> fixed vulnerability in version 5.0.1 or later
postcss version 7.0.36-->fixed vulnerability in version 8.2.13 or later
node-fetch version 2.6.1--> fixed vulnerability in version 2.6.7 or later
nanoid version 3.1.20--> fixed vulnerability in version 3.1.31 or later
glob-parent version 3.1.0 --> fixed vulnerability in version 5.1.2 or later

Please, I would like to know if there is any plan to upgrade these dependencies version in orden to fix the vulnerabilities.

Thanks in advanced

**Comment by kkanakas** [comment]
They are in the roadmap, we plan to address these issues soon

**Comment by petrochuk** [comment]
High severity dependencies were updated on main branch. For moderate ones here is pull request: https://github.com/microsoft/powerplatform-actions/pull/179

**Comment by davidjenni** [comment]
@crivasestrada the dependabot security alerts you mentioned are all caused by the gulp tooling used to build these actions. None of those dependencies are used in the TS/JS code **running** our actions.

Unfortunately, the gulp modules we use in this repo (see the `devDependencies` section in the package.json) do not have yet any updates that address these.
CC: @kkanakas @petrochuk
