### ISSUE TITLE
Powerapps Cli LIbrary

### ISSUE THREAD

**Issue by roshangautam** [microsoft/powerplatform-actions#25]
Any plans on publishing the pac library as a separate npm package?

**Comment by davidjenni** [comment]
no, not as npm package, since the pac CLI is .NET code. Wrapping it into a npm tarball is technically possible, but weird...
Note that the pac CLI windows installer (http://aka.ms/PowerAppsCLI) doesn't contain the CLI itself, but instead is a installer front end over a set of nuget packages, one of them: [Microsoft.PowerApps.CLI](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/)

Directly using the nuget package standalone is an advanced scenario; the supported way to install the CLI is via the Windows installer I mentioned initially: it will not only unpack and lay down the CLI nuget and PCF packages, but also add them to the PATH, and also add automatic update support.

**Comment by roshangautam** [comment]
This is brilliant. Thank you so much for the info, super helpful. This will definitely come in handy while orchestrating inner dev loop tasks. By any chance, do you or someone you know happen to know if [PAC](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/) will support import solution command any time soon?
