### ISSUE TITLE
issue when importing a solution on step convert-to-managed

### ISSUE THREAD

**Issue by neidiom** [microsoft/powerplatform-actions#37]
I am using this GA https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/release-solution-to-prod.yml
and the import fails with this error message 

````
Starting Solution Import: 1/7, 14%.

Import of solution file completed: 2/7, 28%.
Waiting on completion of import job 'dc273664-d71b-4dda-8434-8a8f272f1dbf': 3/7, 42%.

Processing of import job ended at 11/20/2020 7:25 AM after 100% completion: 4/7, 57%.
Import job reported a status of 'SUCCESS': 5/7, 71%.

Unmanaged solution import has completed, starting to publish customizations: 6/7, 85%.

Sorry, the app encountered a not recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:2006bae8-a20c-45d7-b21c-806f98f5ee8c
````

When I log in to the power apps website I can see the solution was imported and I can publish it manually.

**Comment by davidjenni** [comment]
@neidiom - the disappointing part is that the underlying pac CLI had an internal error without displaying the actual error it encountered :-(
I'm filing a bug in our pac CLI bug DB in corpnet to at least have it relay the actual error; I'm closing the issue for now since I couldn't even retrieve the exceptionId from our telemetry either. Sorry for the inconvenience
