### ISSUE TITLE
MFA error on who-am-I action

### ISSUE THREAD

**Issue by anmagnot** [microsoft/powerplatform-actions#76]
Getting the following error connecting to an environment with MFA enabled:

export-from-dev
error: 1: Microsoft PowerApps CLI

Version: 1.5.3+gdf82e3f

Error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

![WhoamI_error_MFA](https://user-images.githubusercontent.com/42215274/117145961-b391df00-ad81-11eb-8311-fd1952982764.png)

**Comment by davidjenni** [comment]
@anmagnot this error is by design: the AAD instance enforces MFA for your interactive user acct (standard for all our MS corp accounts, and for many enterprises' AAD as well).
The best practice that is compatible with AAD CondAccess: create an appID with clientSecret, and configure it as Dataverse ApplicationUser.
This documentation is written for the AzDevOps PP.BT tasks, but it applies as much to the GH Actions here as well:
https://aka.ms/buildtools-spn
